### ISSUE TITLE
Estimated TX fee off by one

### ISSUE THREAD

**Issue by kliyer-ai** [CashScript/cashscript#152] opened 2023-06-30 08:30 UTC
Notice how fee per kb is 999 sats

![image](https://github.com/CashScript/cashscript/assets/27199575/a64ccd91-aa84-43fb-8f69-63f3cadb91a1)

Signed tx hash:
```
020000000170a9cd06f8010380d9e5baad174be99f44d38b74fd806b789e586b2384112f8700000000b304737bb77441c8a092df713d7c12d317986795198a12e79c5a5553d8423e66adea69e2b60bcd60ee85a589167b988fbc3b76c132ea221ad92475c9b464958f41ea40583783cf4121025e96449f9f644fff91d2f43489ca82f77090d2cb8228017132438a5887d08e2749044577916404737bb774143ce4f66e21f6f33e7589e83a96f03fabf77eeca5145e012810801997700335289d52bae19e28c4bb08557a5579ad7b557a9d7bb1755279a9877ba97b879bfefffffffd1701801f0200000000001976a914e14f12c16dbf6183a0d49b5716a292907cfda14988ac2d360000000000001976a914d3849fbb622b83ed176257a07c3d007b2a4407ea88ac2d360000000000001976a9141eae2738602739455bbdf9bdb0962c5f3e7b502388ac2d360000000000001976a91438a0a3e3228d78f5a7b2f81c006b13e50068c58288ac2d360000000000001976a9148767172425afcbcdcc076fdb7116b43cc6933f6c88acfc040000000000001976a91441085f0b2276c858613479be97ce6ddb82c2f99088acfc040000000000001976a9144e37c327e541f62ceb6f39d396c6d43b9ddf2e4588acfc040000000000001976a914c11eba88701a5844225b8caea76317591a2a7a3888acfc040000000000001976a914d0e917a2b6b67e7720e557f1885b14b0bedf78b488acfc040000000000001976a914724adfd881b7232b2794406b1df6369ba31e243988acfc040000000000001976a914d0177e9e6d767b7f2b4054b4726a366c5e53970a88acfc040000000000001976a914a75650e8acd24f563f1636717fa203427ec3d5cc88acfc040000000000001976a9148cd688a06f4eab0a3e5c4d359d283aa7be004a2188acfc040000000000001976a91431df32210becf7bf6bc4ed4384d4e6575d24b5e888acfc040000000000001976a914fabea428fc906beda0ca2a919068e7d744bacb2f88acfc040000000000001976a91477ff13da0cce04c849be162b71934341cd81c47c88acfc040000000000001976a9147f0191de67c0d6981a09a82bdb7dd69efe4b4c9088acfc040000000000001976a914bd598eb2143a93f6ba260ab551e843ce9a26fdab88acfc040000000000001976a91448992d1c6537fe4bfba946173c14be4b547009ca88acfc040000000000001976a914785ff09f24e8bb6f2681d76a0c6a866984ed52a188acfc040000000000001976a914bf305d62101ba617df9a0e475beb67ab717fbaa088acfc040000000000001976a91421bbb7514c0a6074ef11325f4fee75d03e0f1e6788acfc040000000000001976a914fc1e7d9e276ff7c0609e29c7b6b5be9fa52fa68288acfc040000000000001976a914b02e46b5d996dbdafe122fb21302208a4c3c840388acfc040000000000001976a91412af3cf8826ce8dd925ec5501c4c8d3c92f64e7788acfc040000000000001976a91433c46c4f02604fcd85941216594d850110aa7d0388acfc040000000000001976a91405a0c9f50b0102ba7705b500da8251dca1699abf88acfc040000000000001976a914bc67bce5849d82ff39d26943dbe37a1669b4b7e488acfc040000000000001976a91469948cb85b75c5e68a48ee5f8d9b688eb0da699f88acfc040000000000001976a9149b7de20147cad1c3fd29da30540152339385720188acfc040000000000001976a9140d2b6d63d83dfdb675b17c46506203498f79e17888acfc040000000000001976a914d382e03b010173ae4a52bd7bf77b8fb1c2196b1b88acfc040000000000001976a9148fd1d9f262fa3b2e8e2c561ffc04b47bc522926788acfc040000000000001976a91441176086ff01d5d7925610098c2dca29fbecc02d88acfc040000000000001976a914d9d4361fd7d47dafc5d087bff6814bddf2e9706f88acfc040000000000001976a91476da2db55b1aa312a4bda158c6ce504f3ace943288acfc040000000000001976a914372bbd98e6912373939fa726d3c3086084fb852c88acfc040000000000001976a9145853e0300d3b69b90b37640af741146f0d189c1388acfc040000000000001976a914d4e5e1dc0e809ff3de6f8971224c751d76879c2a88acfc040000000000001976a914af79efb3c53ccb1fbeec97906d685e102d77a97f88acfc040000000000001976a91414bcda4b5b7edbb8c906c5b8af2e42a7e99e3e4188acfc040000000000001976a9140e9ee6d268e9994c7937fc204e3a923df5817a5688acfc040000000000001976a9142e5a8d7d468b9f2987e937adc4e44710710caede88acfc040000000000001976a9142c4a1b864b50be14cbe0e368b777c27244d229ba88acfc040000000000001976a91451ca1af61de1a40f316f05c9987dab148278a19c88acfc040000000000001976a914d8d752d24b76b02af5448d2d66dd7ae66bf5168188acfc040000000000001976a914a2a4fca16c73502ae826e4fbce8229cc71412c0a88acfc040000000000001976a914c59415345cbcab9f3289a86bcf32a47a3f6a570088acfc040000000000001976a914be2527c225fe94e75da315829c3bd6385dbba4be88acfc040000000000001976a91466d61f110c0fce71e5b4809524a1b563b5bc67a988acfc040000000000001976a914dab8cc7c8db0d58ebe7e69409041f5a40c253bc688acfc040000000000001976a91478df63fec04d35668d0af3ee4670fc1af493ce5d88acfc040000000000001976a91495efbfeaed42f1a35db3400b8356427de42ef51a88acfc040000000000001976a9149e17146269d3f07c3e03dbde6f30ba3ac063b1b988acfc040000000000001976a9141544d56448489cbaad3889981204cafbdccf174088acfc040000000000001976a914012499bf072150e730b54e6e95d0607732454b8288acfc040000000000001976a914ffec53f856b7d9705ceebead8bfb140ab986175588acfc040000000000001976a914fb43e43d8eae3c3d2b3cf9fc3b846d301f17dca888acfc040000000000001976a914132786c8ca8ecd3e42545dc1c0b16b8f0b00d66788acfc040000000000001976a914cf4d908aaff53b4202738c8576abd478bbbefabb88acfc040000000000001976a914f48f2674cac6ab4726a2f115b8b791436c62a81388acfc040000000000001976a914d7b0348f08bcadb6bb2001b498c40d242e0eb1cc88acfc040000000000001976a9142e99a12963d301e5a8ec238aefa9f954235105aa88acfc040000000000001976a914b02816eb61b74f0b36cbf565d31092f7ca2eefb088acfc040000000000001976a9145af6c72a238c58187449b3cff6e2f7c08aba7b7888acfc040000000000001976a91450163b8f46e1151e4977c628882d23b5bbc69ffb88acfc040000000000001976a9146b2d6a5fcf2fe6eb4e6bd63a65a7dfd41092b80888acfc040000000000001976a914913104222b546c46716379a32a0421f6e6a6c5cc88acfc040000000000001976a914baf5d37c21569becbe0c69e1fb4351ab1a09b82d88acfc040000000000001976a914e9075b79be9b49ebae3100bc6c9454ace330f4af88acfc040000000000001976a914c60c08ed1e5721a20863b71359d1500db72a586888acfc040000000000001976a91476c088dfa7e55be18791b278420a988db55b210488acfc040000000000001976a914b520bc9debe6ad40f780e3269f4780d9895e080c88acfc040000000000001976a91429c3afe0261d88482dc23809a3d8acbf1c34eaed88acfc040000000000001976a914c21f2efdc19f012c572f3759c0b2c3d8d0e0884588acfc040000000000001976a914a6ec4764827ceb07141fc7192909829f42d9cfee88acfc040000000000001976a914db05c929be7147a2bca63fbd7891edc06932041988acfc040000000000001976a914f9e35662ce3701c31c33fa30e5c9fbe393345ed688acfc040000000000001976a9145a187334f481d7f9cdab366a344b3c4ced061f6688acfc040000000000001976a91410731ccd2a4566d17598b0fdcdbb2c84de631cc588acfc040000000000001976a914bc965fe5f875e880beecd43d28aedf2cb7d60a2888acfc040000000000001976a91407d92f8e768363df4f1b6b742a4036491cee0e1688acfc040000000000001976a91445f014366a4289678ffef69f95b15db97faa311888acfc040000000000001976a914366d1f12ee0305bbc8c9e331351182b6d103e71588acfc040000000000001976a9148c7892f47a8db8399b2f01e112ea4ad5cfd6d7d388acfc040000000000001976a914ca1f6bcc3f8a147ecbe0ac999f607c66692a1abd88acfc040000000000001976a914f7349e3020189acdb8ec95c2e41995772199c11088acfc040000000000001976a9146e636060d6cd26618ecbd60ad66f7ffb7ae0cf9f88acfc040000000000001976a914bce9751d48aee40820baa52853c3f21162a390bf88acfc040000000000001976a9140911b5ec97a7d458b840b58db84552b9ce8ace5f88acfc040000000000001976a9145461d119e01be3b3bfc67d4716e6107043d75a9288acfc040000000000001976a9149d205835547a5a62f3905bdf3eaa5f2a84807f6e88acfc040000000000001976a91440459815543960631fff03d0689bd12e00911a6888acfc040000000000001976a91418e3c57a3501f28538222e8392151fcf9027db6288acfc040000000000001976a914abacfabca57e2a149fec62171c34da35c06708a488acfc040000000000001976a914d74004984d3ae4a27d71b31b2b98ffc1ea1b871d88acfc040000000000001976a914118f7301edbdf4aa04ef3297054fe0187c759e9e88acfc040000000000001976a914a80a74f10224fc9b8603d56f5af15b5b53c9c60188acfc040000000000001976a914f59b29506e904f7d50aa5e7faa00fbd3e491bc1388acfc040000000000001976a914d7f36024b882c89d5233a38b8de87782f9336b3b88acfc040000000000001976a914eeef23cbfaa6309733949414f11c4a1629a6216188acfc040000000000001976a914df218e32dfca069cf480ded604542b925931232388acfc040000000000001976a914f52d7655881c222b115d91f54c58826c44d3155d88acfc040000000000001976a9140aaf75c5a9c2352fe78ab265dd6216507205f11288acfc040000000000001976a91414f52ae271b464088ee995d1e076a2c0cd8439fd88acfc040000000000001976a91418b86eb5a034adcb2682cfae23395e1ce723da7688acfc040000000000001976a914b6eed8e04e0365e504913c95c51d3851a3cf2f9d88acfc040000000000001976a914474e7d9347866435107daa6bf7474d35e360128488acfc040000000000001976a914274cc78be0282ee7df335ee21559d7045df6aad688acfc040000000000001976a914518311851567f7caa0512bf17ecac9875e41793488acfc040000000000001976a914b34d9790305c008c8853d5d37cb01b8827cb619a88acfc040000000000001976a914f91272887f1a18558da2b0609441f81538ed9dda88acfc040000000000001976a9143bfd64ffcc07d729c976d3df44df853d0f9aa81a88acfc040000000000001976a914ee2cd7d55c17bc9f5bc66d094ed69928d9699c4c88acfc040000000000001976a9145e0ad165ac59dcbf147419723925526de46cb46488acfc040000000000001976a914c0698d8aad9c8a47f15da80590d44872dfa256f888acfc040000000000001976a914341d2a5c473a4b51529484dac9e3f148d07305b288acfc040000000000001976a9142328f4b468b1e8ac96f96a907348bfdfcb8d753c88acfc040000000000001976a914130f5101e6e7c4870d2ebd487b6892816536cf8688acfc040000000000001976a914a0926d629b502083fc4d0b7021a092d87e87b81788acfc040000000000001976a9141bde5762f44fd4bbe4606793b1d00bf893dd93b388acfc040000000000001976a9141c38ea751b8cb992d23a7e44d9e28a3694cb6b9f88acfc040000000000001976a914b9361881f65c90535e75e22494b4e14237cf283e88acfc040000000000001976a914314c5e20c0d59a7add057863ee4c1b0ea706e96388acfc040000000000001976a914fb5c3a25b013fa4de67791a92e15f2b915aabcd788acfc040000000000001976a914314b11557d26a32b2f8de334c205db6a4ce93d9c88acfc040000000000001976a914bf09073deebf146641dada6ccd6b154d3a4d0ecd88acfc040000000000001976a914ac09640c2091ead7c916fde8c03787c84383076288acfc040000000000001976a91421f85fa2c54b8a5b2bb93634db5abaac0de5d7de88acfc040000000000001976a9142b5028121a4ee80f6a168615365e1fcc535592d588acfc040000000000001976a914ac4c3d6a343619c2d7f0334d3a874cf90098120d88acfc040000000000001976a9140a3aacc1a16dec6d595163f1988f629da127bc4988acfc040000000000001976a9140767083e3286944c60918d2417f6adf23e5051a988acfc040000000000001976a9145bb1ee901cbbcb4561064a05828646c4ea4427a288acfc040000000000001976a9141abd77243bb12099ec41cc6ffde3e90edc64b79388acfc040000000000001976a9149877d3e8a40700abd19fb6bb6cd697efe48b5c2d88acfc040000000000001976a91438dad19b1385d1ff1f81aca48a8fd05fc6bd2d5988acfc040000000000001976a914e2d97d265fc0ab1c41eab51aacc420fb87a2ab6388acfc040000000000001976a914623d5560a895c2005a1ecf88691b802dc6ffd9fa88acfc040000000000001976a91498aa6ef0d3650d780335f1fb1606c3ce8d97b22788acfc040000000000001976a91445d0ff92022dac7266d2ac720d18a638e019df2c88acfc040000000000001976a914612777aae77dc2d57c7a68810e68d38e6940a3ce88acfc040000000000001976a91434b7e1ec25efaad4dc1fa53de95865a07ce5557988acfc040000000000001976a914fa8d3c638b1d85bf8eada7f5785768d5c5f9a01a88acfc040000000000001976a914d4d541b83225976ee670bd3029cf16151f4aed7488acfc040000000000001976a914b87e7a919cae06971407406e0933b9d5f62d066d88acfc040000000000001976a91406145fe6689c591e550ea4c175e430012201456b88acfc040000000000001976a9141645f416156e6171d30668dac46af2e6e3b07bf588acfc040000000000001976a91495bd6e933d48b5919810130236ae759a0d8bbd6488acfc040000000000001976a91473700d4b08c927e574a0a3829db3631e24be8d5f88acfc040000000000001976a91441e56ae0d32915288bbb1642267fb3477eeeac0988acfc040000000000001976a9144e093a1925a4acf3ebd1f6d3fcaae8a062fb8a1688acfc040000000000001976a9149fd8a85f0dcfa57e0c881412372bbaf9bbc20dac88acfc040000000000001976a914be4bda7a25fcc5cd762ff4ac37707240b2ea6a5a88acfc040000000000001976a914c4dc1d81a6a49544f2d8963f0dca289a6df05d0e88acfc040000000000001976a914073544d7c1bfa5281f320c9a189ac058acfcf95088acfc040000000000001976a9144d54b9bc1a7a6ff62c2a69d090df1182964f8e6388acfc040000000000001976a9145606b7b52aee91ff801305b6e4ee2829724a847988acfc040000000000001976a9148a109d2a9acf22303ce28785addd0fb0b39f49e588acfc040000000000001976a914e02b0d9956a0b25574f3bacfec7d13e13e5a913c88acfc040000000000001976a91428e1df5d7b6a97f5bd7acc9a1d3dae3d0128399588acfc040000000000001976a9142cc09b659039ec8f649270d4a0e14a791f569c4588acfc040000000000001976a914b1e83a905d1242b39ba6675fd75bf6dac0e368b788acfc040000000000001976a9140617d20db06db468d9eed8202bf98fb7acfaca2c88acfc040000000000001976a9149a4da9243a54ab14f0a4e2bbbd0e51c21872896488acfc040000000000001976a914f9e4153ac07558d9d3335c44425cf86b4888b7af88acfc040000000000001976a9147f42a54d7b210995ac0d0f112ea8e44f3b44627688acfc040000000000001976a9144090fac8fc2b472dfc8a75f87126fc507232be8588acfc040000000000001976a914d1cd97106a4caf28c8811282b5daee6981f4689688acfc040000000000001976a9146cbc65025264bf2de9454bd465f4c2cc314ae34d88acfc040000000000001976a9147537633fbe9bdbd16f9a776b44c9f13cec24ac7188acfc040000000000001976a91442052b20f91f0699b638abcc3419c16591b3218588acfc040000000000001976a9143c8ad66705abd1521181c57f9fc3f74887ab934588acfc040000000000001976a9140bc62403dc89b39e055818c633f9e3be774c0d3288acfc040000000000001976a9149c7a155ff66be1ccb1d9dd0760e826b5a823ed6b88acfc040000000000001976a914dfec41630ba5c04cfe4b954dd7d94929efb7f7d088acfc040000000000001976a914fe6aadc2b2aefb08a42e4e1e55fa658beaff6a3f88acfc040000000000001976a91465d2d5038da0060131be0914b19ba108023a4ae388acfc040000000000001976a914281d412bd2b5f60bfb4d5e3aa9eb77e7937bd42d88acfc040000000000001976a91467a5c6547b20b18162324fbc6bcfae875644b4a188acfc040000000000001976a9146e55fd8a453c32df11edda29bf77b325ee9690b888acfc040000000000001976a91422b5d041e8bf49eee54551fc07d74dd42b67930788acfc040000000000001976a91474b378e8da40b4602b811176d7c1da38b4978eab88acfc040000000000001976a914e801f5cc277b3bc03c02133c2d37b4f8f2ebd5f788acfc040000000000001976a9149fba33fd258d84a79389f430602d032d336abda988acfc040000000000001976a914ee1148377a297b154ee695f78a9e8b8a33a11e2288acfc040000000000001976a914be797ed5dcdb932184315685296b31e09dc9ffb188acfc040000000000001976a914354009955b5e94dc80e3912e1e006f89b7f65e0d88acfc040000000000001976a914242b47a1fbdc17627d199a96463041b56177198388acfc040000000000001976a914401564c62c9f92de26e167ebbe5466ab07048c8088acfc040000000000001976a914f921a82f37dea77faf36d5052ede0daff8e1e4a788acfc040000000000001976a914b8c84c37ab0b8239ffc42311f5bda14653b2bee688acfc040000000000001976a91483842dcc9a75a404b7c806c78098b0475da43d4788acfc040000000000001976a9144d1806f650e1f7e28913176a5a8a15da62df218488acfc040000000000001976a914da4c4b91c091f88b4f258d1e2af5e2a1755ba93588acfc040000000000001976a914904270048cdcb12f963c5773797abf9523f7d94188acfc040000000000001976a914b7a141ade497e2da1abf95087301598f60fcae9888acfc040000000000001976a914889716ac70bd4e8eb6a3a193c605fd9db263acb588acfc040000000000001976a914c9c7f6ec72a570d1887adaf8577648a0571263ca88acfc040000000000001976a9148ee788d5070bd7fb48c8474ded6cce2bf70794a788acfc040000000000001976a9142273dc323945572daf8df925b65eade4fd1418e588acfc040000000000001976a914b2f1203fa947b0a12e51f11bb08142dd1c614e5a88acfc040000000000001976a9147197bdd51d47443aa601a48b4706770355ad703888acfc040000000000001976a914326af9e930215ed13072d5bfbb7ea84b0c556c3d88acfc040000000000001976a9140be5166628eb2832facf795b8484841275355fcc88acfc040000000000001976a91417580b05bdad7d62052b0c1e05483738345d234a88acfc040000000000001976a914fe00c78e9794dfff26bdb24fd757569e5ad6a26488acfc040000000000001976a914e27f4299b7b1e268f152208bd80888c7800774a688acfc040000000000001976a91419bf5e07db9c04f6f7f3788a74142280e415d60088acfc040000000000001976a914f3ac4a5936432b6b2bce71fffc8db37aca1757e088acfc040000000000001976a914691cbf3d504becbab44b85e0b2a62c5fd17fd40988acfc040000000000001976a914ce3f8efffa8f99959705b92e4235d243ede64b8688acfc040000000000001976a914d62139b8cc8d112b89a8caba1ff8d9bf6262109088acfc040000000000001976a914040c4d3f0c9a1403f6755effe0a9489dd2c43e2088acfc040000000000001976a9145688ef0052b73eb78665d42eecdbefb002e8e59388acfc040000000000001976a914191ddfb11e57f5213b528fd507b91d92459af16588acfc040000000000001976a914651965552a55e66ac4c7d4ff42caaf49e2bad42088acfc040000000000001976a914b1ac247fc3b2a06e400162b523a2ea6e46b7f09088acfc040000000000001976a914fb34fd9df8a65810b9ea4c96e4320be62025e21788acfc040000000000001976a91429437ed3c867eed010a754ae14d0dc8ce222429688acfc040000000000001976a91412cb99022c4de54aad03425bd98a7fabcebf4a5188acfc040000000000001976a91483fba9df6739f27e11bbc1eeb9daebc66851f3dc88acfc040000000000001976a914fe50c738657ac339a331ff64b7d1bb15ce8f330d88acfc040000000000001976a914551dd80d9441a99e2b6b56043b9ccdd8dc4ead8388acfc040000000000001976a914b6d79a13adb535084a53b65e8c66d209e412277e88acfc040000000000001976a91464a2712c6c436f25372cc06492fca3c4008e9a3288acfc040000000000001976a91411c4e8b23b57653d933ecdc9f49a83aa45437ae688acfc040000000000001976a9142e3d001ad5e27b0da0729ba8942a3818399f5aaf88acfc040000000000001976a914a63e3e31787f31e7901549a78372daaa88851fb288acfc040000000000001976a914ac5a75e2174dea8a13023a12ce0bacc5f3d1820788acfc040000000000001976a914c2776d22aa9917c44b48047b434ac83ee9042d1588acfc040000000000001976a91411efc7f3b7ff61cdaa2d01732f560fa742fc68d788acfc040000000000001976a914e9010d01c9925b693b201d20e68453901c95716188acfc040000000000001976a9147e186454643785d6eb70fff04d23370457f8eb1a88acfc040000000000001976a91410ac42ecff58f04bf84bb0af9c850b4efcdd413188acfc040000000000001976a914dbbccaf71c35209bd15aeff2294600e0952c654e88acfc040000000000001976a914d401e5399fda0573dd3e0edffb4711b3b2ef9dc588acfc040000000000001976a914e6dd4b42e2dc6cb50720c50b673f51af8e8a8d8188acfc040000000000001976a914d8245e81f90ec7f215c4254993a282575c9d5eac88acfc040000000000001976a914b6699038c68fdfe15f50f7dc19e08928efdec7ef88acfc040000000000001976a914dbaed1e8dc92d83427e17f618e8310a7862eead488acfc040000000000001976a914887cd3e7a0fc60673379968824bb8b1f6c929c5f88acfc040000000000001976a91419725246ba8533ea606748ae430e60004e38191a88acfc040000000000001976a914f129ce56f90e482ddb525f3101bfa6900e95b9d188acfc040000000000001976a91476486da9772dd4234b8194882ec3ecf6d7b44ab688acfc040000000000001976a9142a525e8b61aa463c294a5de599ffc21393ac450f88acfc040000000000001976a91405d6ad5aef2278fad32cb9e1419cda379f92a4c688acfc040000000000001976a914111630114cb5508d8352fa0a2a4809f337d1d57388acfc040000000000001976a91449445b20308aa6ab6649d100fb86811fbed3bcdb88acfc040000000000001976a9149dafff2fc4ea0965498627fa6ce24e55b3f77f8588acfc040000000000001976a9142c6ed0ee21eb4aa929b2285ce0c3751501dc206488acfc040000000000001976a914f39de040d7f68b7c1aacd34dc7419734ea91045e88acfc040000000000001976a914a22112d7a24316b58b1b853f30c16928ca2d8da588acfc040000000000001976a9143cc3cfb133aaf3e73f0f08ca217d345cc678e33d88acfc040000000000001976a91421bc1600423cb4c869bbad0c2c3c6a8abc7377be88acfc040000000000001976a9143cf5c38ff12b1bf6bf5d574fedbe9c3cf44b8d7988acfc040000000000001976a914c64179bb32db47d77f487c64fb4a43ddc03b3f9988acfc040000000000001976a91497c039f3e6dc16f0c2d7ef0b830745f18f09bdc988acfc040000000000001976a91464a79126bd4fddb971d348a0d039b437b8a736f188acfc040000000000001976a91426932f4760022342a44b414524821010d641993488acfc040000000000001976a914797f90a563decca56676ce7fba0fddd44202205488acfc040000000000001976a914d435c123df566ac3b6221d6e23b30fb0de0df67688acfc040000000000001976a914f66033b7cd278388d9f50cb73fa872ac08746b3a88acfc040000000000001976a91459869dd584220482f34e48c661468c0e55717ee888acfc040000000000001976a9144043e2d3d78d3a9bccdc848490cb0bc03dbbdd0088acfc040000000000001976a91486200d4a020f23ce9159aa0033bf49d5257cf4a888acfc040000000000001976a914268d76f99051a0fbfa551313167130a40b435c8088acfc040000000000001976a9148003e9d08301fd319058ab6f32cbf82d377dc8f988acfc040000000000001976a91474198bc502c7ba9d527f9ce9b9339d38bd9b5f8e88acfc040000000000001976a914c674b9a548dbca7f000f7598734d78cd94766f1288acfc040000000000001976a914345534b463ab60ae3fa719557b78f62e87e2791588acfc040000000000001976a914532cad56dd8b552cba0b85ecc25e5bcc0b1852b788acfc040000000000001976a914ec784a9a3317462c5b7a212a774108d65506f2f088acfc040000000000001976a914823ad4ec5590dcdb47f479e8f3fa954c340f4c0b88acfc040000000000001976a9142ddb0425f5ffb7730ab12b4707f5ce875e0b2d5188acfc040000000000001976a91496e0d5c3600b50440788485b809f9ce3cf1751fe88acfc040000000000001976a91494ed776354fd4b7a73a565094cd83ea65d3b090488acfc040000000000001976a914572b1f8b28da9869e433c056897c5c744995032c88ac4a8400000000000017a91480e48019ca301c5a24d841736690457425ee2b488745779164
```

**Comment by mr-zwets** [comment] 2023-11-01 11:06
This issue was fixed in the 0.9.2 release! The cause of the one-off error was wrong encoding of the VarInt when more than 1 byte is needed to represent the numbers of outputs.

Thanks for finding this bug & reporting the issue!

**Closed by mr-zwets** 2023-11-01 11:06 UTC
